create database customer_behavior;
use Customer_behavior;

-- Q1. what is the total revenue generated by male vs female customers??

select gender, sum(`Purchase Amount`) as revenue 
from customer_behavior
group by gender;

-- Q2. Which customers used a discount but still spent more than the avg purchase amount??

select `Customer ID` , `Purchase Amount`
from customer_behavior
where `Discount Applied` = "Yes" and `Purchase Amount` >= (select avg(`Purchase Amount`) from customer_behavior);

-- Q3. Which are the top 5 products with highest average review rating??

select `Item Purchased`, round(avg(`Review Rating`),2) as "Average Product Rating" 
from customer_behavior
group by `Item Purchased`
order by avg(`Review Rating`) desc
limit 5;

-- Q4. Compare the average purchase amounts between standard and express shipping.

Select `Shipping Type`, 
round(avg (`Purchase Amount`),2) as avg_purchase_amount
from customer_behavior
where `Shipping Type` in ('Standard', 'Express')
group by `Shipping Type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers

select `Subscription Status`, 
count(`Customer Id`) as total_customers,
round(avg (`Purchase Amount`),2) as avg_spend,
round(sum(`Purchase Amount`),2) as total_revenue
from customer_behavior
group by `Subscription Status`
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchase with discounts applied ??

select `Item Purchased` , 
round(100 * sum(case when `Discount Applied`= 'Yes' Then 1 else 0 end)/count(*),2) as discount_rate
from customer_behavior
group by `Item Purchased`
order by discount_rate desc
limit 5;

-- Q7. Separate customers into new , returning and loyal based on their total
-- no. of previous purchases , and show the count of each segment

with customer_type as (
select `Customer ID`, `Previous Purchases`, 
case 
	when `Previous Purchases` = 1 then 'New'
    when `Previous Purchases` between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer_behavior
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category

with item_counts as(
select Category,
`Item Purchased`,
count(`Customer ID`) as total_orders,
row_number() over (partition by category order by count(`Customer ID`) desc) as item_rank
from customer_behavior
group by Category, `Item Purchased`
)

select item_rank, Category, `Item Purchased`, total_orders
from item_counts
where item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe??

select `Subscription Status`,
count(`Customer ID`) as repeat_buyers
from customer_behavior
where `Previous Purchases`>5
group by `Subscription Status`;

-- Q10. What is the revenue countribution of each age group?

select `Age Group`,
sum(`Purchase Amount`) as total_revenue
from customer_behavior
group by `Age Group`
order by total_revenue desc;
